import { McpServerModel } from "@/types/server";

/**
 * MCP服务器数据
 */
export const serverData: McpServerModel[] = [
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@modelcontextprotocol/server-sequential-thinking"]}}]',
    server_id: 41,
    qualified_name: "sequential-thinking",
    display_name: "Sequential Thinking",
    tag: null,
    type: null,
    description: "通过结构化的思维过程提供了一个动态和反思性的问题解决工具",
    created_at: "2025-04-14T07:08:49.000Z",
    updated_at: "2025-04-27T13:37:04.000Z",
    logo: "https://img.alicdn.com/imgextra/i1/O1CN01paqzHu1sBw6jJV4A4_!!6000000005729-2-tps-200-200.png",
    introduction: null,
    use_count: 231,
    repository_id: "",
    package_url:
      "https://www.npmjs.com/package/@modelcontextprotocol/server-sequential-thinking",
    creator: "jspahrsummers",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@playwright/mcp@latest"]}}]',
    server_id: 43,
    qualified_name: "playwright",
    display_name: "Playwright",
    tag: null,
    type: null,
    description:
      "轻松实现网页交互自动化，让你的大语言模型能够在网页上导航、提取数据并执行操作",
    created_at: "2025-04-14T07:10:53.000Z",
    updated_at: "2025-04-27T13:42:38.000Z",
    logo: "https://tosv.byted.org/obj/mcphub/playwright.svg",
    introduction: null,
    use_count: 176,
    repository_id: "",
    package_url: "https://www.npmjs.com/package/@playwright/mcp",
    creator: "pavelfeldman",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@modelcontextprotocol/server-puppeteer"]}}]',
    server_id: 45,
    qualified_name: "puppeteer",
    display_name: "Puppeteer",
    tag: null,
    type: null,
    description: "使用 Puppetter，可进行访问网页、截图、点击页面等操作",
    created_at: "2025-04-14T07:13:51.000Z",
    updated_at: "2025-04-27T13:37:06.000Z",
    logo: "https://tosv.byted.org/obj/mcphub/puppeteer.svg",
    introduction: null,
    use_count: 163,
    repository_id: "",
    package_url:
      "https://www.npmjs.com/package/@modelcontextprotocol/server-puppeteer",
    creator: "jspahrsummers",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["mcp-server-flomo"],"env":{"FLOMO_API_URL":"your_api_url_here"}}}]',
    server_id: 47,
    qualified_name: "mcp-server-flomo",
    display_name: "Flomo",
    tag: null,
    type: null,
    description: "可操作 Flomo，比如创建一篇笔记",
    created_at: "2025-04-14T07:17:50.000Z",
    updated_at: "2025-04-27T05:23:33.000Z",
    logo: "https://flomoapp.com/images/logo-192x192.png",
    introduction: null,
    use_count: 80,
    repository_id: "",
    package_url: "https://www.npmjs.com/package/mcp-server-flomo",
    creator: "xianminx",
    is_domestic: true,
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@modelcontextprotocol/server-gitlab"],"env":{"GITLAB_PERSONAL_ACCESS_TOKEN":"<YOUR_TOKEN>","GITLAB_API_URL":"https://gitlab.com/api/v4"}}}]',
    server_id: 44,
    qualified_name: "gitlab",
    display_name: "GitLab",
    tag: null,
    type: null,
    description:
      "快速操作 GitLab，搜索仓库、创建仓库、更新文件、获取文件内容等",
    created_at: "2025-04-14T07:12:35.000Z",
    updated_at: "2025-04-27T10:42:39.000Z",
    logo: "https://tosv.byted.org/obj/mcphub/gitlab.svg",
    introduction: null,
    use_count: 61,
    repository_id: "",
    package_url:
      "https://www.npmjs.com/package/@modelcontextprotocol/server-gitlab",
    creator: "jspahrsummers",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@kazuph/mcp-fetch"],"env":{}}}]',
    server_id: 52,
    qualified_name: "mcp-fetch",
    display_name: "Fetch",
    tag: null,
    type: null,
    description: "提供网页内容获取功能的 MCP Server",
    created_at: "2025-04-15T06:57:15.000Z",
    updated_at: "2025-04-27T05:23:37.000Z",
    logo: "",
    introduction: null,
    use_count: 52,
    repository_id: "",
    package_url: "https://www.npmjs.com/package/@kazuph/mcp-fetch",
    creator: "kazuph",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@modelcontextprotocol/server-github"],"env":{"GITHUB_PERSONAL_ACCESS_TOKEN":"<YOUR_TOKEN>"}}}]',
    server_id: 40,
    qualified_name: "github",
    display_name: "GitHub",
    tag: null,
    type: null,
    description:
      "通过该工具可操作你的 GitHub，搜索仓库、创建仓库、更新文件、获取文件内容等",
    created_at: "2025-04-14T07:06:18.000Z",
    updated_at: "2025-04-21T12:52:29.000Z",
    logo: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
    introduction: null,
    use_count: 49,
    repository_id: "",
    package_url:
      "https://www.npmjs.com/package/@modelcontextprotocol/server-github",
    creator: "jspahrsummers",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@modelcontextprotocol/server-brave-search"],"env":{"BRAVE_API_KEY":"YOUR_API_KEY_HERE"}}}]',
    server_id: 42,
    qualified_name: "brave-search",
    display_name: "Brave Search",
    tag: null,
    type: null,
    description: "使用 Brave 综合网络搜索和本地搜索功能",
    created_at: "2025-04-14T07:09:37.000Z",
    updated_at: "2025-04-27T05:23:28.000Z",
    logo: "https://tosv.byted.org/obj/mcphub/brave-search.png",
    introduction: null,
    use_count: 20,
    repository_id: "",
    package_url:
      "https://www.npmjs.com/package/@modelcontextprotocol/server-brave-search",
    creator: "jspahrsummers",
  },
  {
    connections:
      '[{"type":"stdio","config":{"command":"npx","args":["-y","@suekou/mcp-notion-server"],"env":{"NOTION_API_TOKEN":"your-integration-token"}}}]',
    server_id: 46,
    qualified_name: "notion",
    display_name: "Notion",
    tag: null,
    type: null,
    description: "可通过 AI 工具操作 Notion",
    created_at: "2025-04-14T07:17:05.000Z",
    updated_at: "2025-04-16T10:00:52.000Z",
    logo: "https://icons.duckduckgo.com/ip3/www.notion.so.ico",
    introduction: null,
    use_count: 19,
    repository_id: "",
    package_url: "https://www.npmjs.com/package/@suekou/mcp-notion-server",
    creator: "suekou",
  },
];
